### ISSUE TITLE
Failed to reproduce 

### ISSUE THREAD

**Issue by AlexTraan** [google-coral/crosstool#1]
Hi Coral team,

My target is cross-compile C/C++ program in Devboard. I intend to use crosstool and bazel to do this.
I follow the guidance of crosstool but failed at step 3, the error message as below:
**bazel build --crosstool_top=@crosstool//:toolchains --compiler=gcc --cpu=aarch64**
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
ERROR: /home/alex/google-coral/crosstool/WORKSPACE:1:1: name 'http_archive' is not defined
ERROR: error loading package '': Encountered error while reading extension file 'configure.bzl': no such package '@coral_crosstool//': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'configure.bzl': no such package '@coral_crosstool//': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.104s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Can you help me?

**Comment by dmitriykovalev** [comment]
Please take a look at https://github.com/google-coral/tflite/blob/master/cpp/examples/lstpu/WORKSPACE for the example setup.

**Comment by dmitriykovalev** [comment]
Please reopen if problem still exists.
