### ISSUE TITLE
What's the use of the toolchain() calls in BUILD.tpl

### ISSUE THREAD

**Issue by samlaf** [google-coral/crosstool#2]
This is just a question to help me understand the code base.

From my understanding, toolchain_suites are made of 3 parts, which in the cc case, are:

1. cc_toolchain_suite
2. cc_toolchain
3. cc_toolchain_config (which actually returns the cctoolchainconfiginfo)

The more general (language agnostic) version is:

1. register a _toolchain rule
2. build targets of this rule (one per platform)
3. for each of the targets in step 2, register a target of the 'toolchain' rule

BUILD.tpl mostly uses the first method, but there are [three calls to toolchain()](https://github.com/google-coral/crosstool/blob/6bcc2261d9fc60dff386b557428d98917f0af491/BUILD.tpl#L129) which I don't understand. Are they necessary?

Many thanks.

**Comment by dmitriykovalev** [comment]
There is some info about toolchains at https://docs.bazel.build/versions/main/toolchains.html. Our code was written at different times by different people. Original version used only `cc_toolchain` for `aarch64`, `armv7`, and `armv6`. Code for `riscv64` and `windows` was added later and now uses `toolchain` in addition to `cc_toolchain`.
